server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    config:
      label: master
      profile: ${spring.profiles.active}
      discovery:
        service-id: config-server
        enabled: true
    gateway:
      routes:
        - id: cosumer
          uri: http://localhost:8081
          predicates:
            - Path=/getDemoService



