server:
  port: 8080

spring:
  application:
    name: ms-service-consumer
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # non-secure-port-enabled: true
    prefer-ip-address: true
