server:
  port: 8081
spring:
  application:
    name: ms-service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    #non-secure-port-enabled: true
    prefer-ip-address: true
