server:
  port: 8888
  context-path: /
spring:
  application:
    name: ms-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
security:
  basic:
    enabled: false
